// svelte_todolist/src/lib/Footer.svelte
<script lang="ts">
  import { deleteBtn } from "../className/btn";
  import { checkedAll, clearDone, list } from "../stores/todolist.svelte";
  const done = $derived(
    $list.reduce((pre, cur) => pre + (cur.done ? 1 : 0), 0)
  );
  const total = $derived($list.length);
</script>

<footer class=" mt-4 flex justify-between items-center">
  <label>
    <input
      disabled={total === 0}
      type="checkbox"
      checked={done === total && total > 0}
      onchange={(e) => checkedAll((e.target as HTMLInputElement).checked)}
    />
    <span class="text-xl">全选</span>
    <span class="text-xl">已完成：{done} / 共：{total} </span>
  </label>
  <button
    disabled={total === 0 || done === 0}
    onclick={clearDone}
    class=" {deleteBtn} disabled:opacity-60">删除已完成</button
  >
</footer>

// vue_todolist/src/components/Footer.vue
<script lang="ts" setup>
    import { computed, ref } from 'vue';
    const props = defineProps<{ checkedAll: checkedAll, clear: clear, list: List }>();
    const done = computed(() => props.list.reduce((pre, cur) => pre += (cur.done ? 1 : 0), 0))
    const total = computed(() => props.list.length)
    const label = computed(() => `以完成 ${done.value} / 共 ${total.value}`)
</script>
<template>
    <q-footer>
        <div class="row justify-between">
            <q-checkbox @update:model-value="(v) => checkedAll(v)" :model-value="done === total" :label="label" />
            <q-btn color="deep-orange" label="清除已完成" @click="clear" />
        </div>
    </q-footer>
</template>
<style scoped></style>
